apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e0ndjpcqi-python
  janus-idp.io/tekton: e0ndjpcqi-python
  backstage.io/kubernetes-id: e0ndjpcqi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e0ndjpcqi-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
